//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebServiceImperial.ServicioImperial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImperial.WebServiceImperialSoap")]
    public interface WebServiceImperialSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarRebelde", ReplyAction="*")]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse AdjuntarRebelde(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarRebelde", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse> AdjuntarRebeldeAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarPlaneta", ReplyAction="*")]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse AdjuntarPlaneta(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarPlaneta", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse> AdjuntarPlanetaAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento datos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarIdentificacion", ReplyAction="*")]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse AdjuntarIdentificacion(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarIdentificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse> AdjuntarIdentificacionAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarRebeldeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarRebelde", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequestBody Body;
        
        public AdjuntarRebeldeRequest() {
        }
        
        public AdjuntarRebeldeRequest(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarRebeldeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public AdjuntarRebeldeRequestBody() {
        }
        
        public AdjuntarRebeldeRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarRebeldeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarRebeldeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponseBody Body;
        
        public AdjuntarRebeldeResponse() {
        }
        
        public AdjuntarRebeldeResponse(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarRebeldeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarRebeldeResult;
        
        public AdjuntarRebeldeResponseBody() {
        }
        
        public AdjuntarRebeldeResponseBody(bool AdjuntarRebeldeResult) {
            this.AdjuntarRebeldeResult = AdjuntarRebeldeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarPlanetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarPlaneta", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequestBody Body;
        
        public AdjuntarPlanetaRequest() {
        }
        
        public AdjuntarPlanetaRequest(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarPlanetaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public AdjuntarPlanetaRequestBody() {
        }
        
        public AdjuntarPlanetaRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarPlanetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarPlanetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponseBody Body;
        
        public AdjuntarPlanetaResponse() {
        }
        
        public AdjuntarPlanetaResponse(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarPlanetaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarPlanetaResult;
        
        public AdjuntarPlanetaResponseBody() {
        }
        
        public AdjuntarPlanetaResponseBody(bool AdjuntarPlanetaResult) {
            this.AdjuntarPlanetaResult = AdjuntarPlanetaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarIdentificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarIdentificacion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequestBody Body;
        
        public AdjuntarIdentificacionRequest() {
        }
        
        public AdjuntarIdentificacionRequest(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarIdentificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.ArrayOfString datos;
        
        public AdjuntarIdentificacionRequestBody() {
        }
        
        public AdjuntarIdentificacionRequestBody(ClienteWebServiceImperial.ServicioImperial.ArrayOfString datos) {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarIdentificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarIdentificacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponseBody Body;
        
        public AdjuntarIdentificacionResponse() {
        }
        
        public AdjuntarIdentificacionResponse(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarIdentificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarIdentificacionResult;
        
        public AdjuntarIdentificacionResponseBody() {
        }
        
        public AdjuntarIdentificacionResponseBody(bool AdjuntarIdentificacionResult) {
            this.AdjuntarIdentificacionResult = AdjuntarIdentificacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceImperialSoapChannel : ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceImperialSoapClient : System.ServiceModel.ClientBase<ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap>, ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap {
        
        public WebServiceImperialSoapClient() {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarRebelde(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest request) {
            return base.Channel.AdjuntarRebelde(request);
        }
        
        public bool AdjuntarRebelde(string nombre) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequestBody();
            inValue.Body.nombre = nombre;
            ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse retVal = ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarRebelde(inValue);
            return retVal.Body.AdjuntarRebeldeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse> ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarRebeldeAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest request) {
            return base.Channel.AdjuntarRebeldeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeResponse> AdjuntarRebeldeAsync(string nombre) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarRebeldeRequestBody();
            inValue.Body.nombre = nombre;
            return ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarRebeldeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarPlaneta(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest request) {
            return base.Channel.AdjuntarPlaneta(request);
        }
        
        public bool AdjuntarPlaneta(string nombre) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequestBody();
            inValue.Body.nombre = nombre;
            ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse retVal = ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarPlaneta(inValue);
            return retVal.Body.AdjuntarPlanetaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse> ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarPlanetaAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest request) {
            return base.Channel.AdjuntarPlanetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaResponse> AdjuntarPlanetaAsync(string nombre) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarPlanetaRequestBody();
            inValue.Body.nombre = nombre;
            return ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarPlanetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarIdentificacion(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest request) {
            return base.Channel.AdjuntarIdentificacion(request);
        }
        
        public bool AdjuntarIdentificacion(ClienteWebServiceImperial.ServicioImperial.ArrayOfString datos) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequestBody();
            inValue.Body.datos = datos;
            ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse retVal = ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarIdentificacion(inValue);
            return retVal.Body.AdjuntarIdentificacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse> ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap.AdjuntarIdentificacionAsync(ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest request) {
            return base.Channel.AdjuntarIdentificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionResponse> AdjuntarIdentificacionAsync(ClienteWebServiceImperial.ServicioImperial.ArrayOfString datos) {
            ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest inValue = new ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequest();
            inValue.Body = new ClienteWebServiceImperial.ServicioImperial.AdjuntarIdentificacionRequestBody();
            inValue.Body.datos = datos;
            return ((ClienteWebServiceImperial.ServicioImperial.WebServiceImperialSoap)(this)).AdjuntarIdentificacionAsync(inValue);
        }
    }
}
