//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectImperiales.ServicioImperialTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImperialTest.WebServiceImperialSoap")]
    public interface WebServiceImperialSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarRebelde", ReplyAction="*")]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse AdjuntarRebelde(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarRebelde", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse> AdjuntarRebeldeAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarPlaneta", ReplyAction="*")]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse AdjuntarPlaneta(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarPlaneta", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse> AdjuntarPlanetaAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento datos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarIdentificacion", ReplyAction="*")]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse AdjuntarIdentificacion(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjuntarIdentificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse> AdjuntarIdentificacionAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarRebeldeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarRebelde", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequestBody Body;
        
        public AdjuntarRebeldeRequest() {
        }
        
        public AdjuntarRebeldeRequest(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarRebeldeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public AdjuntarRebeldeRequestBody() {
        }
        
        public AdjuntarRebeldeRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarRebeldeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarRebeldeResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponseBody Body;
        
        public AdjuntarRebeldeResponse() {
        }
        
        public AdjuntarRebeldeResponse(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarRebeldeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarRebeldeResult;
        
        public AdjuntarRebeldeResponseBody() {
        }
        
        public AdjuntarRebeldeResponseBody(bool AdjuntarRebeldeResult) {
            this.AdjuntarRebeldeResult = AdjuntarRebeldeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarPlanetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarPlaneta", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequestBody Body;
        
        public AdjuntarPlanetaRequest() {
        }
        
        public AdjuntarPlanetaRequest(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarPlanetaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public AdjuntarPlanetaRequestBody() {
        }
        
        public AdjuntarPlanetaRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarPlanetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarPlanetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponseBody Body;
        
        public AdjuntarPlanetaResponse() {
        }
        
        public AdjuntarPlanetaResponse(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarPlanetaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarPlanetaResult;
        
        public AdjuntarPlanetaResponseBody() {
        }
        
        public AdjuntarPlanetaResponseBody(bool AdjuntarPlanetaResult) {
            this.AdjuntarPlanetaResult = AdjuntarPlanetaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarIdentificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarIdentificacion", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequestBody Body;
        
        public AdjuntarIdentificacionRequest() {
        }
        
        public AdjuntarIdentificacionRequest(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarIdentificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.ArrayOfString datos;
        
        public AdjuntarIdentificacionRequestBody() {
        }
        
        public AdjuntarIdentificacionRequestBody(UnitTestProjectImperiales.ServicioImperialTest.ArrayOfString datos) {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdjuntarIdentificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdjuntarIdentificacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponseBody Body;
        
        public AdjuntarIdentificacionResponse() {
        }
        
        public AdjuntarIdentificacionResponse(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdjuntarIdentificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdjuntarIdentificacionResult;
        
        public AdjuntarIdentificacionResponseBody() {
        }
        
        public AdjuntarIdentificacionResponseBody(bool AdjuntarIdentificacionResult) {
            this.AdjuntarIdentificacionResult = AdjuntarIdentificacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceImperialSoapChannel : UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceImperialSoapClient : System.ServiceModel.ClientBase<UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap>, UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap {
        
        public WebServiceImperialSoapClient() {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarRebelde(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest request) {
            return base.Channel.AdjuntarRebelde(request);
        }
        
        public bool AdjuntarRebelde(string nombre) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequestBody();
            inValue.Body.nombre = nombre;
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse retVal = ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarRebelde(inValue);
            return retVal.Body.AdjuntarRebeldeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse> UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarRebeldeAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest request) {
            return base.Channel.AdjuntarRebeldeAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeResponse> AdjuntarRebeldeAsync(string nombre) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarRebeldeRequestBody();
            inValue.Body.nombre = nombre;
            return ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarRebeldeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarPlaneta(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest request) {
            return base.Channel.AdjuntarPlaneta(request);
        }
        
        public bool AdjuntarPlaneta(string nombre) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequestBody();
            inValue.Body.nombre = nombre;
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse retVal = ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarPlaneta(inValue);
            return retVal.Body.AdjuntarPlanetaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse> UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarPlanetaAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest request) {
            return base.Channel.AdjuntarPlanetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaResponse> AdjuntarPlanetaAsync(string nombre) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarPlanetaRequestBody();
            inValue.Body.nombre = nombre;
            return ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarPlanetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarIdentificacion(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest request) {
            return base.Channel.AdjuntarIdentificacion(request);
        }
        
        public bool AdjuntarIdentificacion(UnitTestProjectImperiales.ServicioImperialTest.ArrayOfString datos) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequestBody();
            inValue.Body.datos = datos;
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse retVal = ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarIdentificacion(inValue);
            return retVal.Body.AdjuntarIdentificacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse> UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap.AdjuntarIdentificacionAsync(UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest request) {
            return base.Channel.AdjuntarIdentificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionResponse> AdjuntarIdentificacionAsync(UnitTestProjectImperiales.ServicioImperialTest.ArrayOfString datos) {
            UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest inValue = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequest();
            inValue.Body = new UnitTestProjectImperiales.ServicioImperialTest.AdjuntarIdentificacionRequestBody();
            inValue.Body.datos = datos;
            return ((UnitTestProjectImperiales.ServicioImperialTest.WebServiceImperialSoap)(this)).AdjuntarIdentificacionAsync(inValue);
        }
    }
}
